name: Docker Image CI for GHCR

on: 
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the image
              run: |
                docker login --username Dracon1023 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/dracon1023/booking-services-frontend:latest --file Dockerfile .
                docker push ghcr.io/dracon1023/booking-services-frontend:latest
            - name: Publish the image to harbor
              run: |
                docker login c8n.io -u alexandermd1023@gmail.com -p qCdSLjxbTZz8Ia6lfEGieM9CkHOfmiFW
                docker tag ghcr.io/dracon1023/booking-services-frontend:latest c8n.io/dracon1023/booking-services-frontend:latest
                docker push c8n.io/dracon1023/booking-services-frontend:latest